name: Raghav K. Chhetri
markdown: kramdown
permalink: /scattered.dimes/:year/:month/:day/:title
description: Will be exploring ideas and depositing them here
google_analytics: [Your Google Analytics tracking ID]

theme: jekyll-theme-cayman